name: Publish Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: [self-hosted, mgmtjbox-web-test-runner]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set KUBECONFIG
        run: echo "KUBECONFIG=/home/user/.kube/config" >> $GITHUB_ENV

      - name: Verify kubectl access
        run: kubectl get nodes

      - name: Publish site to Kubernetes
        run: kubectl apply -f /home/user/code/kubernetes/website-with-ci-updated-example/publisher.yaml
